services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-22-bookworm
    volumes:
      - ..:/workspaces/trajviz:cached
    ports:
      - 4000:4000
      - 5173:5173
    command: /bin/sh -c "while sleep 1000; do :; done"
    networks:
      - TrajNet
  redis:
    image: redis:7
    networks:
      - TrajNet

networks:
  TrajNet:
    driver: bridge